name: Build
on:
  pull_request:
    paths:
      - '.github/workflows/build.yaml'
      - '**.sublime-syntax'
      - '**/syntax_test_*'
      - '**.tmPreferences'
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/build.yaml'
      - '**.sublime-syntax'
      - '**/syntax_test_*'
      - '**.tmPreferences'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: 'latest'
          - build: 'stable'
          - build: 4077  # `version: 2` support

    steps:
      - uses: actions/checkout@v6

      - name: Install SBNF
        uses: baptiste0928/cargo-install@v3.4.0
        with:
          crate: sbnfc

      - name: Compile syntax file
        run: sbnf usfm.sbnf

      - name: Run syntax tests (${{ matrix.build }})
        uses: SublimeText/syntax-test-action@v2
        with:
          build: ${{ matrix.build }}
          package_name: 'USFM Bible'
