name: Build
on:
  workflow_call:

env:
  PKG_NAME: 'USFM Bible'
  PKG_FILE: 'USFM Bible.sublime-package'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install SBNF
        uses: baptiste0928/cargo-install@v3.4.0
        with:
          crate: sbnfc

      - name: Compile SBNF syntax
        run: sbnf usfm.sbnf

      - name: Create ST package
        run: zip '${{ env.PKG_FILE }}' *.md *.tmPreferences *.sublime-syntax tests/**

      - name: Upload ST package
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.PKG_FILE }}
          archive: false
          if-no-files-found: error
